### ISSUE TITLE
No module named 'folium'

### ISSUE THREAD

**Issue by adeckert23** [learn-co-curriculum/nearest-neighbors-lab#15]
In terminal, i enter: !pip install folium, and the response I get is this:
-bash: !pip: event not found

I've entered this into the terminal (pip install -r requirements.txt), and I get this:
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by mas16** [comment]
Hi adeckert23, thanks for letting us know. The folium installation instructions have been updated.
