### ISSUE TITLE
installing folium

### ISSUE THREAD

**Issue by mgavish** [learn-co-curriculum/nearest-neighbors-lab#16]
I'd change the language to say to past 'pip install -r requirements.txt' into **jupyter** instead of 'your terminal' (my interpretation was to actually install it on my computer) and also, the installation code is missing the ! so, should be !pip install -r requirements.txt.

**Comment by JordanTreDaniel** [comment]
I agree completley!! ^^

**Comment by mas16** [comment]
Hi mgavish! Thanks for letting us know. The folium installation instructions have been updated.
