### ISSUE TITLE
Important Typo in Instructions

### ISSUE THREAD

**Issue by jmarkdaniels** [learn-co-curriculum/nearest-neighbors-lab#18]
I just discovered that my issues with installing Folium in the Nearest Neighbors Lab was because of a missing '!'. The instructions don't say anything about putting the command in as "!pip install folium". Instead it just says to enter "pip install folium". The instructions also direct you to input these commands in a terminal. That doesn't work either.....or rather it doesn't work without the "!". Maybe others with more experience with Python automatically know to include that "!" for all pip commands, but for those of us who are new to the language, this issue can take a while to figure out.

**Comment by jayascript** [comment]
When installing requirements through a Notebook, one should prepend the command with `!`. Doing so is how you can access the shell/terminal directly through your Notebook. If you are installing the requirement directly in the terminal, you shouldn't need the `!`. `pip install [package name]` should work just fine. If it doesn't, you might need to call `pip3 install` if you're using a newer version of Python 3. 

That being said, package management is a huge hurdle for beginners, so perhaps it would be good to include a short section or lesson that dives a bit deeper into how to get all packages up and running.

**Comment by mas16** [comment]
Hi jmarkdaniels! Thank you for pointing this out! The folium installation instructions have been updated.
