### ISSUE TITLE
Confusing wording

### ISSUE THREAD

**Issue by banana-onion** [learn-co-curriculum/nearest-neighbors-lab#22]
"Ok, next write a function called distance_between_neighbors that adds a new key-value pair, called distance_from_selected, that **calculates** the distance of the neighbor_trip from the selected_trip."

I think you mean "indicates" rather than "calculates" here? This makes it sound like this function should do the same thing as the distance_location function. I found the instructions here VERY confusing. The only way I was able to figure out what the functions were supposed to do, was to look at the answers.

**Comment by mas16** [comment]
Thanks banana-onion! The wording has been changed.
