### ISSUE TITLE
distance_location

### ISSUE THREAD

**Issue by Jojanna** [learn-co-curriculum/nearest-neighbors-lab#23]
What are the units for the distance between pickup points for the "distance_location" function? The code suggests that the answer is ~0.235. The answer I come out with by implementing the haversine formula is 21.7 km. Using external calculators on the input lat/longs, my implementation appears to be correct. I do not know where 0.235 comes from - it is not in miles. Has something got muddled?

**Comment by Jojanna** [comment]
Pythagoras on lat/long?! Oh... I guess it's just an exercise! :(

**Comment by mas16** [comment]
Hi Jojanna, the units for the distance are in decimal degrees like the lat/long coordinates. You are correct in pointing out that the precise distance must take into account the curvature of the surface of the earth using the haversine formula which this calculation does not.
